apiVersion: v1
kind: Pod
metadata:
  name: application-news
spec:
  containers:
  - name: container-applications
    image: jnlucas/image-phpmysql:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
