apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-application-news
spec:
  selector:
    matchLabels: 
      name: application-pod
  template:
    metadata:
      labels:
        name: application-pod
    spec:
      containers:
        - name: container-applications-store
          image: gpoleze/alura-news-portal:latest
          resources:
            requests:
              cpu: "200m"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: service-application-news
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30001
  selector:
    name: application-pod
