apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-system
spec:
  selector:
    matchLabels:
      name: system-pod
  template:
    metadata:
      labels:
        name: system-pod
    spec:
      containers:
        - name: container-system
          image: gpoleze/alura-news-system
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
             - containerPort: 8080