apiVersion: v1
kind: Service
metadata: 
  name: service-stateful-system
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30002
  selector:
    name: statefulset-system-pod
