apiVersion: v1
kind: Service
metadata: 
  name: service-application-news
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30001
  selector:
    name: application-pod
